[package]
name = "lrpeg"
version = "0.4.1"
authors = ["Sean Young <sean@mess.org>"]
description = "Left recursive PEG parser generator"
repository = "https://github.com/seanyoung/lrpeg"
keywords = [ "parser", "generator", "peg", "left-recursive" ]
categories = ["parsing"]
edition = "2021"
readme = "../README.md"
license = "MIT"
workspace = ".."

[dependencies]
onig = "6.3.1"
unicode-xid = "0.2"
