[package]
name = "lrpeg-test"
version = "0.1.0"
authors = ["Sean Young <sean@mess.org>"]
edition = "2021"

[build-dependencies]
lrpeg = { path = "../lrpeg" }

[dependencies]
lrpeg = { path = "../lrpeg" }
regex = "1.5.4"
unicode-xid = "0.2.2"
