name: test
on: [push, pull_request]
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --tests --bins -- -D warnings
      - name: Run tests
        run: cargo test
      - name: Re-generate PEG parser
        run: cargo run src/peg.peg > peg.rs &&  mv peg.rs src/peg.rs
        working-directory: ./lrpeg/
      - name: Test
        run: cargo build && cargo test

